package io.Petrov_Todor.enums;

public enum TypeBooks {
    AUTOBIOGRAPHY, BUSSNESS, CHILDREN_BOOKS, CLASSIC, ECONIMICS, ENCYCLOPEDIA, DRAMA, FANTASY, HORROR, MYSTERY, GUIDE, TRUE_CRIME, PARANORMAL_ROMANCE, SCIENCE
}
